### ISSUE TITLE
Flexible usage of DataTable class

### ISSUE THREAD

**Issue by slizovskiy** [bgrimstad/splinter#48]
Hi!   Imagine I have multi-dimensional DataTable  and I want to find it's maximal Y element  in some X - slice (defined by, e.g. x(0), x(5)  fixed).   Is there a smart way to do this without scanning over all the Data? 
Thanks,
Sergey

**Comment by gablank** [comment]
Hello, Sergey.

No, there is no easy way to do this. However, assuming that your grid is complete and that there are no duplicates, I believe you should be able to do it with some arithmetics.

Internally the DataTable has a std::multiset of DataSamples, which is stored in increasing order according to the values of their x vectors. The x's are compared as if they were in "big endian" order, that is, if two samples have x' = (0, 9) and x'' = (1, 0), then x' will be stored first. Because the DataSamples are stored in order internally, you know where the grid points will be located, and thus you should be able to only access those elements.

F.ex., assuming you have two dimensional data, with x_vec = (x0, x1), and your grid is: x0: (0, 1, 2) and x1: (0, 1, 2). Your samples would then look like this:
0, 0, y0
0, 1, y1
0, 2, y2
1, 0, y3
1, 1, y4
1, 2, y5
2, 0, y6
2, 1, y7
2, 2, y8
If you want to find the maximum where x0 is 1, then you know that you only have to read the locations from cbegin+3 to (and including) cbegin+5, where cbegin is the iterator returned by DataTable::cbegin.

This is a solution from the top of my head, and I apologize if it does not work (I have not tested it, just wrote down the first solution I could think of). The arithmetic might get hairy, so I would not recommend doing this (unless you want the practice). Maybe @bgrimstad has a better idea of what to do?

May I ask why you don't want to iterate over all samples? Even with hundreds of thousands of samples I imagine the time usage will be pretty low, as this should be an O(n) operation.

Anyway, thank you for your interest in SPLINTER. If you have any feedback we would love to hear it!

**Comment by bgrimstad** [comment]
Hello Sergey,

I would suggest the same solution as the one posted by @gablank. The data is sorted in X so extracting the slice requires some arithmetic only. Unfortunately, DataTable do not have this functionality built in - we have considered it to be out of scope of this library. Finding the largest element in a slice of size n is equivalent sorting the elements and would require O(n*log(n)) operations.

Tip: if your work requires extensive use of slicing I would like to suggest that you implement (or at least prototype) in Python (w/ numpy) or Matlab, which has better support for such operations. SPLINTER has an interface to both of them.
