### ISSUE TITLE
Multi-dimensional control points

### ISSUE THREAD

**Issue by giorgiomarcias** [bgrimstad/splinter#65]
It would be great if the coefficients of the splines weren't limited to 1D points, in order to have one single object spline instead of as many as the desired dimension. That is, consider splines as functions _f_: **R**^m -> **R**^n.
So, for example, one could create space curves of a parameter C(_t_): **R** -> **R**^3

**Comment by gablank** [comment]
If I'm understanding you correctly, you are suggesting adding interpolation of functions with multiple outputs. We used to have that before, but we removed the functionality because it was equivalent to considering the multiple outputs as multiple functions and interpolating on that instead. That is, if your function is **R** -> **R**^3, you would make three B-splines with one output each instead of one B-spline with three outputs.

Do you have a use case where having that functionality would be considerably better than the alternative?

Thanks for taking the time to submit this issue!

**Comment by giorgiomarcias** [comment]
I'm working on 2D and 3D curves, and it would be just code/performance/memory saving to have one B-spline instead of three. For example, given a set of **R**^_n_ data points, one would have to compute the approximating coefficients (and solve a linear system) just once and not _n_.
From a theoretic perspective, it's also a more general and complete support to the math of splines.

I know that it's not so important, but it would be great.

Thanks anyway :-)

**Comment by bgrimstad** [comment]
Hello @giorgiomarcias. I agree that this would make the library more complete from a theoretic viewpoint. As @gablank already said, the library previously supported vector fields **R**^m ->**R**^n. We decided to change it to **R**^m ->**R** mainly to simplify the interface to evalHessian, which needed to return a third order tensor for vector fields (which we handled by stacking a lot of matrices on top of each other). This change may have been a bit short-sighted.

We will consider returning to supporting vector fields with one B-spline object. It is not a big change, but it would break the current interface.

**Comment by giorgiomarcias** [comment]
Thank you so much. I appreciate it a lot

**Comment by bgrimstad** [comment]
Support for multi-dimensional control points has been added in the feature branch [multidim-control-points](https://github.com/bgrimstad/splinter/tree/multidim-control-points). This feature will be available in the next release, which currently is scheduled to be ready in June.

**Comment by bgrimstad** [comment]
This functionality has been added, tested, and marked for inclusion in upcoming v.4.0 release. Closing.
